"""Add Speed Challenge and Memory Game tables

Revision ID: add_new_games
Revises: add_gamification_tables
Create Date: 2025-08-18 23:58:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_new_games'
down_revision = 'add_gamification_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create speed_challenges table
    op.create_table('speed_challenges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('total_questions', sa.Integer(), nullable=True),
        sa.Column('questions_answered', sa.Integer(), nullable=True),
        sa.Column('correct_answers', sa.Integer(), nullable=True),
        sa.Column('incorrect_answers', sa.Integer(), nullable=True),
        sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
        sa.Column('time_remaining_seconds', sa.Integer(), nullable=True),
        sa.Column('average_response_time', sa.Float(), nullable=True),
        sa.Column('fastest_response_time', sa.Float(), nullable=True),
        sa.Column('slowest_response_time', sa.Float(), nullable=True),
        sa.Column('streak_count', sa.Integer(), nullable=True),
        sa.Column('max_streak', sa.Integer(), nullable=True),
        sa.Column('game_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speed_challenges_id'), 'speed_challenges', ['id'], unique=False)
    
    # Create memory_games table
    op.create_table('memory_games',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('total_cards', sa.Integer(), nullable=True),
        sa.Column('cards_revealed', sa.Integer(), nullable=True),
        sa.Column('matches_found', sa.Integer(), nullable=True),
        sa.Column('moves_count', sa.Integer(), nullable=True),
        sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
        sa.Column('time_remaining_seconds', sa.Integer(), nullable=True),
        sa.Column('revealed_cards', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('matched_pairs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('game_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_games_id'), 'memory_games', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_games_id'), table_name='memory_games')
    op.drop_table('memory_games')
    op.drop_index(op.f('ix_speed_challenges_id'), table_name='speed_challenges')
    op.drop_table('speed_challenges')
    # ### end Alembic commands ###
